services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public_html:/var/www/html
      - ./apache.conf:/etc/apache2/conf-enabled/custom.conf
      - ./data:/var/www/data
    ports:
      - "80:80"